### ISSUE TITLE
Download list of 'Places" into a Google sheet file for client DICI.CA

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1133]
Download list of Places from the "alepoint" aggregator into a Google sheet file.  Client will then indicate the appropriate MRC region on the Google sheet to be re-uploaded into Places.

Calendar ID: 657199fea5ac3d006314ea92

**Comment by troughc** [comment]
@dev-aravind @sahalali the MRC/ region (which now goes by the standard field "District") is not showing up in the bulk download file for swagger. I think it's a bug because "Region" is in the file. Please look at attachment. 
For example, Amphitheatre Cogeco (https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/places/65dc6895bec01b00642c5e54) has a destrict, which doesn't appear in the attached spreadsheet 
Can you fix this ASAP and and provide the bulk download of places for tomorrow?  

[export-csv-file_Place-de4cb384-5cea-48e5-94f8-cb1db0fd05c7.csv](https://github.com/user-attachments/files/15537325/export-csv-file_Place-de4cb384-5cea-48e5-94f8-cb1db0fd05c7.csv)

**Comment by troughc** [comment]
@tammy-culture here is the 'report' of places so you can use it to sort on the aggregator as needed.

@dev-aravind I also noticed that district isn't included in the report. My bad, I missed that field. Can you please add a column for the district field? Thanks.

[Place_report (1).csv](https://github.com/user-attachments/files/15537399/Place_report.1.csv)

**Comment by dev-aravind** [comment]
@troughc I fixed both of the issues that you mentioned, the district is now available in the generateReport API and also the bulk export. Please review this and let me know if you find any issues.

**Comment by troughc** [comment]
@dev-aravind aI tested in staging, looks good. Just a couple questions.

For bulk export, I noticed that the heading row still says 'region' instead of Distict. but maybe that doesn't matter - is it automatically generated?

[export-csv-file_Place-14a681ad-14a2-43eb-ade8-2dabb1654587.csv](https://github.com/user-attachments/files/15596413/export-csv-file_Place-14a681ad-14a2-43eb-ade8-2dabb1654587.csv)


For report, would it be possile you rename the **french** column for district to **NomDuQuartierFR**
If not, no worries.

[Place_report (3).csv](https://github.com/user-attachments/files/15596503/Place_report.3.csv)

**Comment by troughc** [comment]
Either way, please deploy to production @dev-aravind. Thanks!

**Comment by dev-aravind** [comment]
@troughc The district french name is changed to NomDuQuartierFR in the report now.
