### ISSUE TITLE
General Error 

### ISSUE THREAD

**Issue by kmdvs** [culturecreates/footlight-app#1162]
General error, unfortunately a while ago, I can't remember what happened prior... 

![Footlight Test error](https://github.com/culturecreates/footlight-app/assets/44624797/695b1eac-0b3a-40f1-a513-3ec1fa9c745d)

**Comment by troughc** [comment]
@AbhishekPAnil sorry i forgot to assign this to you.

**Comment by AbhishekPAnil** [comment]
Bug report : This happened because the calendarId passed to the api had the value undefined.We had added a fix for this in the past week.This shouldn't be happening anymore in cms.
If you want to test it out ,you can pass the calendarId as undefined in the URL.Similar to this: https://staging.cms.footlight.io/dashboard/undefined/events?page=1&order=asc&sortBy=upcomingEventDate&publication=Draft.
If at all we manually add calendarId as undefined like in the above url ,,it would force the cms to fallback to the last know calendarId.We had already fixed the issue where calendarId was getting undefined while logging in.

**Comment by troughc** [comment]
@kmdvs please take a look at this and then I will close it.

**Comment by kmdvs** [comment]
I didn't have this error in the last weeks. I think it can be closed :)
