### ISSUE TITLE
Mandatory fields in ArtscultureNB - not showing up in events workspace with a red asterisk

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1194]
The issue is in Production and Staging and may be present in other calendars. I tested it in ArtscultureNB. See steps to reproduce below.
**Note:** This message from the customer prompted me to test this. In his scenario, Audience was required but Audience was missing from the Event form in production so he could not publish an event. I think this means that the Admin was able to set Audience to Mandatory but it was not being displayed in Events. Why would that be? 
Please investigate. Message:
_I created an event for testing purposes but it wasn’t letting me publish it - I was getting this message below, and from looking at the browser console it was expecting a ‘Target Audience’ field which wasn’t on the page at that time. That field is there now, so... I was able to publish the test event._

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/964254fc-413e-455a-b041-b8f6123e98f0)

 

**Steps to reproduce my bug in STAGING:**
1. Open a new or existing event. Notice that Event type doesn't have an asterisk.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/8a7ca23f-4965-4d9a-9643-86b0e5d34fa6)

2. Look in Mandatory fields. Event type is mandatory.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/6b7dcea7-3cdd-437b-b2cd-843dc9cde79f)

3. Now, in an event, fill in all Mandatory fields (don't fill in Event type). Click Publish. Notice the message at the top. Notice that event type is not highlighted red.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/3f1864ff-251c-4d0a-9494-41e656eb41b4)

4. Fill in event type. Click Publish. Notice the message at the top. It is unknown what is blocking.

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/c8aefe26-a325-4ca0-908f-d0d00e0abeaa)

**Comment by sahalali** [comment]
@troughcI've found the main cause of this issue. This particular problem arises in the ArtsCultureNB calendar and it involves two issues:
1. According to the calendar configuration in the database, the following fields are mandatory for publishing an event: EVENT_TYPE, AUDIENCE, NAME, DESCRIPTION, TICKET_INFO, START_DATE, LOCATION, IMAGE, and ORGANIZER. However, no taxonomy is mapped to the standard field "Audience" in the calendar, so the option for an audience will not appear in the event form. This could confuse users as they won't realize that the "Audience" field is mandatory.
2. The back-end validation also fails when the audience field is missing in the event.

Proposal:
1. Show the audience option in the UI event if no taxonomy is mapped to it and display the red asterisks to indicate the mandatory field. Additionally, the listing of mandatory fields in the calendar menu should not omit the standard fields that are not mapped to any taxonomy. Otherwise, it will confuse.
2. This issue will be resolved once the data-centric approach for the Event form is designed and implemented.


cc @saumier

**Comment by sahalali** [comment]
As a workaround, let's create a taxonomy for the audience and map it, or remove the audience from the mandatory field list if it's not required.

**Comment by troughc** [comment]
I will retest once the production and cms are aligned to see if both the mandatory fields list and event form are good. 

I will also test to see what happens if I delete a taxonomony - will it disappear from mandatory fields and from event (workspace) form

**Comment by sahalali** [comment]
The data has been successfully copied from the production environment to the staging environment. The issue that was hindering the data copy process has been resolved.

Please take note of the following instructions:
@troughc, to initiate the data copy from the production environment to the staging environment, follow the steps below:
1. Navigate to the following URL: https://github.com/culturecreates/footlight-calendar-api/actions/workflows/database-restore-staging.yml
2. Click on "Run workflow" to initiate the data copy process.


![Image](https://github.com/culturecreates/footlight-app/assets/139197166/1f14b424-ffde-4a8c-8c85-455327de96bb)


3. Select the branch as Master.


![Image](https://github.com/culturecreates/footlight-app/assets/139197166/d92d28f5-ab70-4707-8a10-94e1f4e8e4b9)


4. Click on "Run workflow"


![Image](https://github.com/culturecreates/footlight-app/assets/139197166/ced714a4-e0fa-43e9-bc7e-694548d4bfd1)

**Comment by troughc** [comment]
Tested that I could delete the taxonomy and the mandatory field and field in the workspace were also deleted: PASSED
Tested that asterisks appear when I make a field mandatory according to the problem logged in this issue: PASSED
Note that there is another known issue being addressed in issue #1195 (and others) that affects mandatory fields (pending)
Ready to deploy at the appropriate moment.

**Comment by troughc** [comment]
Note before deploying @sahalali - there is an issue #1221  in staging that is not present in production. please be aware so as not to introduce it to production. thank you.
