### ISSUE TITLE
Tourisme Mauricie was unable to publish event because two types in Mandatory fields.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1216]
Mandatory fields has two 'Type' options in Events. One works (the one I selected) and the other is a 'ghost in the machine'. Please take a look.

Also, is this related to https://github.com/culturecreates/footlight-app/issues/1195? YES

**Comment by tammy-culture** [comment]
@sahalali Tourisme Mauricie is unable to set this event to Publish on the CMS.
https://cms.footlight.io/dashboard/661e5a8818a64f7829aeae24/events/add-event/6669571b7a706500645d3bd2

They see the following error message



![Image](https://github.com/culturecreates/footlight-app/assets/45608438/011c9dcd-5bd8-4d72-9a57-5164669f9e81)

Even though they have filled in all the mandatory information.

I tried it and was also unable to set this event to publish.  I took care to fill in all the mandatory fields.

Please take a look as soon as you can.

Thanks.

**Comment by troughc** [comment]
ArtsCultureNB also could not publish because there are also 2 Audiences (not one). I switched it and was able to publish.

Screenshot of 2 audiences in mandatory fields:
![Image](https://github.com/culturecreates/footlight-app/assets/64489312/b7bed148-83e5-4614-88be-5e62cd5c568a)

**Comment by troughc** [comment]
@sahalali @AbhishekPAnil @SyamBabu-M this is also happening to Signe Laval ane we can assume it is happening in all calendars. So this issue is high priority.

In Signe Laval, Maude logged this bug:
https://github.com/culturecreates/tech-support-tickets/issues/73 
The issue there is 'Disciplines' (which was renamed from Event type)
Screenshot of 'Disciplines' two times:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/d99d268b-de51-4ffe-aeec-a775449d3515)

**Comment by troughc** [comment]
Tested the issue that was causing this: PASSED.
@tammy-culture we will also be fixing a related issue later today or tomorrow that doesn't allow the Admin to update/change mandatory field settings. So hold off telling customers to start working on mandatory fields for a bit.
