### ISSUE TITLE
All users must go through read-only page before going to edit page in cms.

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#1223]

**Comment by troughc** [comment]
This is looking really good, just one thing: when I am logged in as the Admin, I still see the messages that would appear for guests/contributors who cannot access the event. For example, I see the 'this event has been published'....

Expected behavior: the admin would not see these messages.

screenshot:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/8347386e-3a6e-4416-9783-2daf2a2a44e0)

**Comment by SyamBabu-M** [comment]
@troughc I will work on these changes.
