### ISSUE TITLE
Cannot edit geo-coordinates and they do not save after editing

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#1294]
As a user of CMS, I sometimes want to manually edit the geo-coordinates of a Place.

Expected behaviour:
1. I edit the geo-coordinates in the form
2. The geo-coordinates are updated

Current behaviour:
The geo-coordinates are not saved.

Discovered by client issue in tech support https://github.com/culturecreates/tech-support-tickets/issues/81

**Comment by sahalali** [comment]
This seems to be a FE bug. The payload for the update place API has he old coordinates even when they are updated.

**Comment by troughc** [comment]
@AbhishekPAnil actually, I am not sure it is working correctly. Please see [this place](https://cms.footlight.io/dashboard/63457978637093005071a053/places/add-place?id=66d8c6113451310064481d35)

I had added these coordinates, which I copied from another place. 
45.5539513
-73.704322

After saving, 'undefined' was appended.

**Comment by troughc** [comment]
@saumier maybe you could help with this as I don't really feel knowledgeable about how to add geo-coordinates effectively. Also, Places require a user to add a street address and postal code, even if they put in geo-coordinates. I am wondering if they should have to do that if they put in geo-coordinates?
thanks.

**Comment by AbhishekPAnil** [comment]
> [@AbhishekPAnil](https://github.com/AbhishekPAnil) actually, I am not sure it is working correctly. Please see [this place](https://cms.footlight.io/dashboard/63457978637093005071a053/places/add-place?id=66d8c6113451310064481d35)
> 
> I had added these coordinates, which I copied from another place. 45.5539513 -73.704322
> 
> After saving, 'undefined' was appended.

Bug report :
45.4279614,-75.7252341 This is the usual formatting of geocoordinates in the text field with a comma separation.
The issue happened because while you copy pasted the coordinates ,instead of a comma separation it was an empty space 
45.5539513 -73.704322.Should we handle this also ?

**Comment by troughc** [comment]
Here are the format styles I was able to find. 
What is the format for geo coordinates?
Here are examples of formats that work: Decimal degrees (DD): 41.40338, 2.17403. Degrees, minutes, and seconds (DMS): 41°24'12.2"N 2°10'26.5"E.

**Comment by saumier** [comment]
@troughc @AbhishekPAnil  My thoughts on geo-coordinates are in this discussion https://github.com/culturecreates/artsdata-data-model/discussions/126

**Comment by troughc** [comment]
@AbhishekPAnil and @saumier,  ArtscultureNB is having a Production bug with geo-coordinates and Artsdata. I think it may be related to what you are working on. 
**This is high priority to fix**

Benjamin (the customer) said that the geo-coordinates disappear after he adds them and saves them. Here is a [link to an example place in staging](https://staging.cms.footlight.io/dashboard/65eeaf8ebec01b0064312f94/places/66901b00ee118d00649c6c29)

This place is one that Benjamin edited and then noticed that the geo-coordinates disappeared.
cc @tammy-culture fyi


Here is what he wrote by email
_...I wanted to let you know that there might be a bug or issue regarding GPS coordinates on Footlight. The coordinates vanish everytime a place seems to be updated from Artsdata. This is for instance the case for the Centre culturel Aberdeen, the Fredericton Playhouse, etc. Without coordinates, events do show up on our website but they don't show up on the map._

_Aberdeen Cultural Centre is a good exemple: Mike told me that the GPS coordinates were missing. I added them, and the info got transferred on Arts Culture NB because the centre showed up on the map. But yesterday I realized the coordinates were missing again, and I noticed this afternoon that the data was once again missing on Footlight._

_I updated Aberdeen since, but the same thing happened with other entries. You can take a look at the Fredericton Playhouse, or the Capitol Theatre... Basically every place that got linked to Artsdata seems to reset their GPS coordinates to a null value at some point._

**Comment by AbhishekPAnil** [comment]
Caitlin will discuss with Stephanie about adding a map to the cms for pin pointing coordinates.

**Comment by troughc** [comment]
I don't know if this is pertinent but here is an example of a park location with the pin (the park) and another using the same address that doesn't give the exact same result. If you enter the park name, you get one pin location, if you enter JUST the address you get another pin location. Both are using plus codes in google.

### Address only (No park)
<img width="1142" alt="Screenshot 2024-09-13 at 11 06 31 AM" src="https://github.com/user-attachments/assets/4d4233da-749c-4686-b455-4283fce660c9">

### Park name (uses same street address)
<img width="1227" alt="Screenshot 2024-09-13 at 11 06 19 AM" src="https://github.com/user-attachments/assets/9751da6d-9c69-4a49-9884-5559bac8ee0f">

**Comment by troughc** [comment]
Here is another example https://canadianpowwows.ca/events/kamloopa-powwow/
On this site they give a street address. I can then look it up in google using the name of the place (which gives one location without a street address) or the street address (which gives another location, a little bit away from the place).
### How location is listed on the website
![Image](https://github.com/user-attachments/assets/627cb27d-fc65-4136-8360-36c9c8a95187)


### Enter name of place, which includes town name, into Google (Kamloops Powwow Grounds)
![Image](https://github.com/user-attachments/assets/f90dbe1e-016f-4c12-b6cc-71cbb2f1a6fe)


### Enter street address and city only into Google

![Image](https://github.com/user-attachments/assets/fb44599f-2b67-4dbe-ac20-3f7a02a20b8d)

**Comment by troughc** [comment]
@AbhishekPAnil please use this figma to design: https://www.figma.com/design/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?node-id=3690-77232&t=MBZ4etllDXSpI0vO-1

**Comment by AbhishekPAnil** [comment]
@troughc Will add the user flow in the address fields.

**Comment by troughc** [comment]
DRAFT - WIP 
@saumier can you please take a look so we can discuss during office hours.

Expected use case:
1. Create or edit a Place to enter the Edit/New place form.
2. In the Address section, do one of the following:

MOST COMMON USE CASE - SEARCH: 
- User searches to find the place (by address or by geo-coordinates). In this case, the address fields are automatically filled in, geo-coordinates are added, and the map updates to display the pin location that matches geo coordinates/address data.
- the user can then move the pin if they want to fine-tune a location (drag, click, whatever the module supports by default for gestural editing). If they drag the pin, the geo coordinates update to match the new location.  The other address fields would normally not need to update, because the pin wouldn't be moved very far. However, if the user drags the pin to a different KNOWN address, the fields can update to reflect the change.

RARE USE CASE - MANUAL entry without search: 
User enters an address manually field by field without searching first. In this case, EITHER street address and postal code are required fields OR Geo coordinates is required. 
- If Geo coordinates are NOT added manually, but the address is recognized, geo coordinates could be added automatically and the map would update to display pin location accordingly. 
- If Geo coordinates ARE added manually, the map would update to display the pin location accordingly; other address fields should be filled automatically with what is known about the geo-coordinate location (for example, all fields could be filled including street address: only city, province, county could be filled; Only province and country - whatever is available).
- After the address is added, the user can move the pin if they want to fine-tune the location. If they drag the pin, the geo coordinates update to match the new location. The other address fields would normally not need to update. However, if the user drags the pin to a different KNOWN address, the fields should update.

3. User can delete data from fields if they want. If they delete geo-coordinates, the map pin would be removed.

**Comment by troughc** [comment]
@AbhishekPAnil @saumier, I reviewed the use case with @tammy-culture  and it is good to go. 
Ready for you @AbhishekPAnil, let me know if you have questions, concerns.

**Comment by AbhishekPAnil** [comment]
@saumier The old `Marker` in Google Maps is being deprecated, and it's recommended to switch to the new `AdvancedMarkerElement`. To make this change, along with the existing API key, we will also need a `mapId`, which is required to display markers. You can follow the steps to add a map ID at this link:
 https://developers.google.com/maps/documentation/get-map-id

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil Don't add the search inside the street address field (For the time being ,it may cause a loop issue across address fields).

**Comment by troughc** [comment]
@saumier I tested this and it looks good to me (PASSED)

I think it would be good if you tested it as well, so I am assigning it to you. If you think it works well, please update it to be deployed. Thank you.
