### ISSUE TITLE
Unsaved changes pop up comes while saving an entity

### ISSUE THREAD

**Issue by AbhishekPAnil** [culturecreates/footlight-app#1405]
When saving an entity (Organization, Person, or Place), the "unsaved changes" popup incorrectly appears.

Steps to reproduce:

1. Create an entity.
2. Click save.

- Upon clicking "Save": The "unsaved changes" popup appears, followed by the successful save message.
- Upon clicking "Cancel": The save confirmation message appears, and the user remains on the edit page.

Current behavior: The "unsaved changes" popup appears, even though the entity is successfully saved.

Expected behavior: The "unsaved changes" popup should not appear when saving an entity.

![Image](https://github.com/user-attachments/assets/b2cb3b01-c0e1-443a-9398-f732a87a9bce)

**Comment by troughc** [comment]
@AbhishekPAnil where am I to test this? I tried staging and the bug was there. 
I then tried [this pr](https://pr-1403.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/organizations?page=1&order=asc&sortBy=name) and the bug was NOT there...but maybe I am looking in the wrong places :)

**Comment by AbhishekPAnil** [comment]
@troughc Sorry.I think I forgot to link the PR.I thought I had linked it.Please refer to this [PR ](https://pr-1406.dla06mbe0wyl7.amplifyapp.com)https://pr-1406.dla06mbe0wyl7.amplifyapp.com/ link attatched

**Comment by troughc** [comment]
TESTED: PASSED
