### ISSUE TITLE
Cosmetic fixes

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#17]
## Test feedback from Caitlin

- [x] Alignment issues (already noted by Abhishek) - fix alignment issues in display (space at bottom of pagination, alignment on left side of mobile view et cetera)
- [x] Pagination bug - when navigate to page 2 of event list, and then do a search, it doesn't return to page 1. You stay on page 2 and are stuck unable to see the results on page 1.
- [x] Calendar list (ENHANCEMENT) dropdown for calendars - if only one calendar, you don't need to use a dropdown menu; only use this dropdown component if the user has access to more than one calendar.
- [x] Calendar list - when you switch to Signe Laval, the name 'Signe Laval' is missing. 
- [x] Calendar list - the font for Tout Culture becomes the wrong size for the calendar name after selection (as shown during the demo). It doesn't reset to the right size. If you select Signe Laval and go back, it's fixed (until the next time).
- [x] Calendar list - remove the second line with member info - only display the logo (image) and calendar name everywhere (including drop-down)
- [x] Search field (ENHANCEMENT)- please add a 'x' so we can clear the search field and reset the display to show everything.
- [x] Date display: replace MONTH number with first 3 letters of month, as shown in the FIGMA (sprint 11). For example 02-11-2022 becomes 02-NOV-2022. Do this everywhere in the event list (at the top of each event and the section on the right - this should be 'Updated 30-NOV-2022 by gfinch')
- [ ] Date display: above the title, I think the font colour is not quite right (maybe a bit darker than the figma?) Not sure....
- [x] MOBILE context menu: Publish event, Unpublish event, Delete event -  Fix right-click menu for event state in MOBILE (not being displayed) 
- [x] images and text in event list - Images look stretched vertically (check aspect ratio and size) - they should fill the square without distortion (like CSS property object-fit: cover;)
- [x] The text block beside the images (date, title, place) should be centre-aligned to image for both full screen and tablet versions (see figma)
- [x] the spacing between the calendar dropdown and other left nav items is too close (see Figma)
- [x] username - should be lowercase and consistent everywhere (in username at top and in event list. For example, in event list, change 'gregory finch' to 'gfinch' (depending on how the user was entered first and last name). Gregory Finch becomes gfinch; Gregory Saumier-Finch becomes gsaumier-finch. if First and last names are First Last, the username is 'flast'.  **--> Backend issue assigned to Suhail to supply both first and last names to Abhishek https://github.com/culturecreates/footlight-calendar-api/issues/229**
- [x] "Vérifiez votre courriel" screen - text size of different fields (for example default text in Code de réinitialisation à 6 chiffres) are not all the same. Also true on ENGLISH screen.
- [x] in french version Replace the month number with 3 first letters of the month. for example 02-FEB-2022 would be 02-FEV-2022

**Comment by troughc** [comment]
@saumier I am reviewing the french event details screen and here is some new feedback for you to triage. 
- page one and two sometimes the username is strange (see screenshot) - it has a + admin in brackets? 
- Also, (see on page one) there is a space in the username for Modifié entry 

![Image](https://user-images.githubusercontent.com/64489312/205380473-c18eabe5-9b51-4927-9d75-de0b1445a7e3.png)

- in french version Change yellow label text from Attente D'approbation to Attente d'approbation (do not capitalize the 'D')
- in french version Replace the month number with 3 first letters of the month. for example 02-02-2022 would be 02-FEV-2022
- shares same issues as listed already (examples - search field needs an x; sizing issue with calendar list dropdown; alignment and spacing issues, date display (already mentioned)  
- Thre is an EN beside a title - Guylaine Tanguay EN Is it part of the title or does it mean something else?
- small detail but when I click the other sections, the placeholder text is in english. Probably doen'st matter. (example click Lieux, see Places on a blank page).
- spelling error for event tag in french: 1 événements (shouldn't have an s and proablby shouldn't be there at all);  21 événementss (has 2 ss at the end). See in screenshot.

**Comment by saumier** [comment]
I am moving the french label changes to a separate issue

**Comment by saumier** [comment]
@troughc I entered my last name as "Finch (+admin)" so the user name is behaving as expected.

**Comment by saumier** [comment]
@troughc Please test on staging.cms.footlight.io.

**Comment by saumier** [comment]
@AbhishekPAnil To address the french version month number with 3 first letters of the month I did some research and found that there was no standard 3 letter abbreviations of months in French. I spoke with Caitlin and I decided to use the actual month number. I created a component called FormatDate.js to encapsulate this logic. I also removed moment.js as it was not needed. I commited these changes back into the same branch #bugfix/17 and merged my proposal for the [bugfix/issue-17-switch-language](https://github.com/culturecreates/footlight-app/tree/bugfix/issue-17-switch-language)

**Comment by troughc** [comment]
**Calendar list (ENHANCEMENT) dropdown for calendars - if only one calendar, you don't need to use a dropdown menu; only use this dropdown component if the user has access to more than one calendar.**
- Failed myTEST:

1.  I logged in as caitlin+guest (collaborator on tout culture but NOT on signe laval). 
2. The dropdown is there and shows both calendars. 
3. I switch from Tout Culture to Signe Laval and I STILL see the tout culture events.
4. I refresh the browser (reload) and the Event page is now blank for signe laval (no events are shown).
5. I switch back to tout culture and see my tout culture events (they are displayed).
6. I repeated these steps multiple times with always the same results.

Also, found a little bug - when I am logged in as an Admin with access to both calendars, it doesn't switch properly from tout culture to Signe laval if I am on PAGE 2. It takes me to a blank screen with no way to navigate. I logged this in a separate issue. (47, assigned to gregory)

**Calendar list - when you switch to Signe Laval, the name 'Signe Laval' is missing.**
- this is fixed in all versions except MOBILE - the name "Signe Laval" isn't displayed on mobile.

**Search field (ENHANCEMENT)- please add a 'x' so we can clear the search field and reset the display to show everything.**
 - the x in the search fields, removes the text but does not reset the view to display all the events. I have to refresh.


**Date display: replace MONTH number with first 3 letters of month, as shown in the FIGMA (sprint 11). For example 02-11-2022 becomes 02-NOV-2022. Do this everywhere in the event list (at the top of each event and the section on the right - this should be 'Updated 30-NOV-2022 by gfinch')**
This is good except one odd thing. For the event "Cafe Rencontre"- 0-DEC-2022 is the date displayed. December 0, 2022 doesn't exist -it is not a valid date. Should there be a block from entering bad dates?

MOBILE: on mobile version (android google phone) the + evenement button is on top of the calendar page title. They don't fit.
This is still true in French version on mobile.

Context menu - it is now included in mobile and shows only those options that matter (i.e. if published, it only includes unpublish and delete).  Yay thank you!

**Comment by saumier** [comment]
@AbhishekPAnil Please fix these remaining cosmetic issues found by Caitlin:
- [ ] MOBILE: on mobile version (android google phone) the + evenement button is on top of the calendar page title. They don't fit. This is still true in French version on mobile.
- [ ] Search field (ENHANCEMENT)- please add a 'x' so we can clear the search field and reset the display to show everything. The x in the search fields, removes the text but does not reset the view to display all the events. I have to refresh.
- [ ] Calendar list - when you switch to Signe Laval, the name 'Signe Laval' is missing. This is fixed in all versions except MOBILE - the name "Signe Laval" isn't displayed on mobile.
- [ ] Calendar list (ENHANCEMENT) dropdown for calendars - if only one calendar, you don't need to use a dropdown menu; only use this dropdown component if the user has access to more than one calendar. Not working - see repro steps below:

Reproduction steps for Calendar drop down bug:
1. I logged in as caitlin+guest (collaborator on tout culture but NOT on signe laval).
1. The dropdown is there and shows both calendars.
1. I switch from Tout Culture to Signe Laval and I STILL see the tout culture events.
1. I refresh the browser (reload) and the Event page is now blank for signe laval (no events are shown).
1. I switch back to tout culture and see my tout culture events (they are displayed).
1. I repeated these steps multiple times with always the same results.

**Comment by troughc** [comment]
One note: the main problem with the last issue (calendar dropdown) is: as caitlin+guest, I shouldn't be able to navigate to Signe Laval at all as I am NOT a member of that calendar.

**Comment by saumier** [comment]
@troughc  Please test that last 2  cosmetic issues tracked here (see 2 check boxes above). You can test in production.

**Comment by troughc** [comment]
Looks good. - 2 cosmetic issues above PASSED. 👍 
@saumier I would close this issue, but not sure if the calendar switch issue is logged somewhere else. I leave it for you to close.

**Comment by saumier** [comment]
@troughc Yes the calendar switch has its own issue #50
