### ISSUE TITLE
Link Place to event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#20]
As a user, I can add a location to my event by searching for places that are already used in my calendar.

Add Place using a simple entity search box that searches Footlight Places. Only a single select is allowed. Display a simple entity box including name, disambiguating description, icon and delete button.  No maps, region, complete address or linked data needs to be displayed for MVP.

![Image](https://user-images.githubusercontent.com/419491/211657952-a89e53ca-eab3-450e-8bcd-ea7af474f06b.png)

**Comment by saumier** [comment]
@SuhailAliyar We should design this feature together. We need to ask ourselves questions like "who is responsible to querying Artsdata - the front end or the back end?"

**Comment by SuhailAliyar** [comment]
As we discussed, the Arts data APIs can be called from front end and persist the Artsdata ID/wiki data ID for the linked entities within sameAs objects.

**Comment by saumier** [comment]
@SuhailAliyar Due to the code freeze on January 27th, I have reduced the scope to only link Places in Footlight, similar to the way the oldcms works. We will resume the work of linking to Artsdata after the launch.

**Comment by troughc** [comment]
Tested - Passed

**Comment by saumier** [comment]
@AbhishekPAnil As discussed, please move the selected entity outside of the search box once it is selected.

**Comment by saumier** [comment]
@AbhishekPAnil I reviewed the direction with Caitlin and we are both happy. Please adjust the alignment. Should be as in previous version. The width of the drop-down should match the width of the search field. The drop-down should start just below the search field. Also check both directions when the drop-down appears above and below the search field.

**Comment by troughc** [comment]
Tested in Chrome and found the following issues (also see issue #25 which have same fixes to be made):
1. The dropdown is in the way when you have the field positioned in the middle of the browser. Also, the dropdown is not the same width as the field - it should be aligned and same width. 

![Image](https://user-images.githubusercontent.com/64489312/219503084-9ebe18aa-ac1a-4f19-81f5-418c8dbfd07c.png)

2. The items in the dropdown are not highlighted when my mouse is hovering over them or when I'm using down/up arrows to scroll through the list of items. It is also not highlighted as I select the item (the Place I want). An item should be highlighted during a selection action. 
Note that, if I reopen the dropdown, the item would no longer be highlighted as it is a new search and it takes up real estate.

3. When I press enter during a search action in the field, the entire event closes - <Enter> seems to save the event rather than make the selection. For example, I press Enter when I type in a search name for an organization. Enter shoudl save my choice.

3. The dropdown should close when i select the Place. Right now it remains open. 

4. BUG: I click a second time in the field, the dropdown is closed. I then type in the field (which is still selected) to search for a Place, nothing is displayed. I have to click in the field again to display the search results in the dropdown. This is also a problem in the issue #25 

5. I noticed a small object below the middle of the search field when i enter a search that has no results (see screenshot)

![Image](https://user-images.githubusercontent.com/64489312/219506413-b2a41f1d-df2f-48a1-a277-485d4e45e7f9.png)

**Comment by AbhishekPAnil** [comment]
![Image](https://user-images.githubusercontent.com/117100211/220632080-1df5dcec-dae5-40e9-a3c3-10c91c14656c.png)

7.Reduce the spacing betweeen the dropdown and the search input.

**Comment by troughc** [comment]
everything is okay except issue 3 above (same as in #25 )

**Comment by troughc** [comment]
Tested: PASSED
