### ISSUE TITLE
Link Organizer, Performer, Supporter

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#25]
Add Organizer, Performer, Supporter using a simple entity search box that search Footlight people and organizations. Multiple select allowed. Display a simple entity box including name, disambiguating description, icon and delete button. No roles needed for MVP.

**Comment by saumier** [comment]
@AbhishekPAnil Please go ahead to implement this now that @SuhailAliyar has added the new API to search across multiple entities. You will need to call it by passing both types: Person and Organization like this. http://staging.api.cms.footlight.io/entities?search-key=[string goes here]&classes=Person&classes=Organization

**Comment by troughc** [comment]
Tested on Chrome. 
Sometimes when I click the x to remove an organizer (person / organization) it doesn't respond.
Also, when I click the x, the list of organizers is displayed with the selected objects. I can remove an organization from this list (de-select it).
 
To retest, add a few organizers and then try to remove them one by one using the x. Sometimes it works, sometimes it doesn't so please try a few times.

**Comment by saumier** [comment]
@AbhishekPAnil Lets discuss Friday after our standup meeting. Maybe we can revisit the design.

**Comment by troughc** [comment]
Tested in Chrome and found the following issues (some of the same issue are also true for places):
1. The dropdown is in the way when you have the field positioned in the middle of the browser. Also, the dropdown is not the same width as the field - it should be aligned and same width. (see screenshot)

![Image](https://user-images.githubusercontent.com/64489312/219503084-9ebe18aa-ac1a-4f19-81f5-418c8dbfd07c.png)

2. The items in the dropdown are not highlighted when my mouse is hovering over them or when I'm using down/up arrows to scroll through the list of items. It is also not highlighted as I select an item (and I can do multiple selects). An item should be highlighted during a selection action. 
Note that, if I reopen the dropdown, the item should no longer be highlighted as it is a new search and it takes up real estate.

3. When I press enter during a search action in the field, the entire event closes - <Enter> seems to save the event rather than make the selection. For example, I press Enter when I type in a search name for an organization. Enter shoudl save my choice.

3. TO DISCUSS FURTHER: should the dropdown close after each single selection (by search or by dropdown), i.e. I only add one item at a time? So, if you need to add a second or third item (organizer, performer, supporter), you would click in the field to reopen the dropdown (or simply type in the field a new search string. This is good if the common case is to add one. vs multiples.

4. I find it strange that if I click 2 times in the field it opens and closes the dropdown I can do this multiple times

5. I noticed a small object below the middle of the search field when i enter a search that has no results (see screenshot)

![Image](https://user-images.githubusercontent.com/64489312/219506413-b2a41f1d-df2f-48a1-a277-485d4e45e7f9.png)

**Comment by AbhishekPAnil** [comment]
![Image](https://user-images.githubusercontent.com/117100211/220632307-6df33f01-5637-4ed4-a3fd-c815110c02c8.png)

7.Remove the spacing between the dropdown and search inputs for organizer,performer and supporter.

**Comment by troughc** [comment]
Tested: PASSED

**Comment by AbhishekPAnil** [comment]
@troughc  The way it is working now means that anything I have changed/entered would be unsaved. Can you change that behavior?----------->

I have removed this behaviour now and deployed it in staging.Now when the user clicks Enter after searching ,the user wont be taken out,but I haven't added the option to select an option using the Enter key.I will need to look into it.

**Comment by troughc** [comment]
@AbhishekPAnil I have tested this and it works - I am no longer taken out of the event, thank you.
For the Enter key behavior, don't worry about it, let's treat it as a separate issue (I will talk with Stephanie/Gregory and figure out what we want). 
So I am reassigning this one to me and closing it. Thanks!

**Comment by troughc** [comment]
Tested - PASSED
