### ISSUE TITLE
Too big image: message takes too long to appear

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#282]
When i add an image that is too large (over 5 mb), it takes a very long time for the "unable to complete the request" and 'try a different image' messages to appear (around 10- 15 seconds)
See my test events here:
http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/643d49ef72c0360065a352fe (this is the event where I also tried to add a too large image)

**Comment by troughc** [comment]
@saumier can I have a status on this? Are very large images loading very slowly still an issue?

**Comment by saumier** [comment]
@troughc We redid the image upload section. I am not aware of large images loading slowly. Please test.

**Comment by troughc** [comment]
@saumier I just tested this with this event: http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6494abc4bee1c1006405fbec
First: It took a long time to save (at least 6 seconds by my stopwatch). So I don't think it is resolved.


Second I tried again with one called test test caitlin test in staging. I clicked the button (save) multiple times and ended up with multiple events. It looks like that issue is still not fixed.

see screenshot
<img width="834" alt="Screenshot 2023-06-22 at 4 22 35 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/b984cf5c-3162-4529-aabb-ff5caf87ed80">

**Comment by saumier** [comment]
@troughc Please share a link to your image. I have tested with large images of 3.5 MB without any issues. Also, this bug is to display the message that the image cannot be uploaded. That message is no longer appearing. 

For the "clicked the button (save) multiple times" please report that in the issue that refers to it. It is a different issue. Thx.

**Comment by troughc** [comment]
<img width="451" alt="Screen Shot 2022-07-25 at 4 51 35 PM" src="https://github.com/culturecreates/footlight-app/assets/64489312/3961f5c6-a6ad-4a45-a3f3-a01985bcb045">
@saumier Here you go. It is smaller than yours. (2.4 MB)

**Comment by saumier** [comment]
@troughc I tried you image (2.4 MB) and had no issues.  There is no longer any message. The upload only happens when you click save. Now that the save is "disabled" during the image upload to prevent duplicate events being created, I don't see any other issues. If you get a message "unable to complete the request" and 'try a different image' please take a screen shot.

Assigning back to you.
