### ISSUE TITLE
Search/sort/filter for organization Org, Person, Place

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#419]
As a user, I can search, sort and filter the list of entities.

Tasks
======
- [x] Add/Reuse filter and search components
- [x] Add the api integration to implement search
- [x] Add the api implementation to filter(sort and order).
- [x] Add  the persisting of filters.

Toggles
======

Uses the same toggle as the list view

**Comment by troughc** [comment]
@AbhishekPAnil @SuhailAliyar 
How is the Sort function supposed to work? It doesn't behave the way I expect for any of the entities (including Events)
For example, one time it seemed like words that started with a vowel that was accented (for example É) was put at the end of the list. These should be mixed in with the unaccented letter, alphabetisized by the second letter - for example, like this order (a-z):  École; Espace; Étudiant (c comes before s, comes before t)
Also I don't understand how NAME sorts. See screenshot. (not alphabetical):


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/e0d35ffa-f66d-4a20-9e99-85ed4b7671f5)

**Comment by troughc** [comment]
Additional comment: the name sort seems to be alphabetical per page but not across the entire dataset.

**Comment by sahalali** [comment]
@troughc To your above questions:
**First**: As we have multilingual labels, the sort can be done either with English label (nam.en) or with French label (name.fr) individually. Additionally, we can also sort by combinations (name.en, name.fr), which means sort by English, and then if any duplicate English labels then it considers the French one. We also support sorting in both directions using the functions asc() and desc(). 
Why the accented labels appear at the bottom because according to ASCII encoding, the accented labels appear after Z.
**Second**:  The sort is applied to the matches found from the database with the search.  
Eg: If the user search 'b', then all the Places containing a 'b' in the place name will be fetched, and parallelly the sort will be applied. Both operations are done at the database level.
**Third**: In order to make the search fuzzy, what we have done is, ignore each vowel in the search key, escape special chars. 
Eg: if the user search with 'entrade', the result will contain labels including 'entrede' or 'entryde' but no 'entraide'. Its because a single character is ignored in the search in place of a vowel.

**Comment by sahalali** [comment]
@troughc  Please suggest the next steps with this issue.

**Comment by saumier** [comment]
@troughc The separate issue for alphabetization is https://github.com/culturecreates/footlight-calendar-api/issues/386

**Comment by troughc** [comment]
Hi @AbhishekPAnil I am reopening this issue because there is a pagination issue - PLACES are repeating themselves over different pages. For example, see Signe Laval places. These screenshots show Bibliothèque Multiculturelle appearing on both page 1 and page 3 (they have the same ID when you click them). 

### Page 1


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/5ceddf7a-920d-41ce-a5f8-3060328f7cd1)

### Page 3

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/6fdc597f-6be3-4bca-8f75-d7b575badfb6)

 This is also happening for Places in Tout Culture. See screenshots of page 1 and 2 both include AXENÉO7. 


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/61ddfbcb-b149-4b2e-9af2-f95e4dbcd1bc)



![Image](https://github.com/culturecreates/footlight-app/assets/64489312/ba7d2007-f647-4458-9394-f85db5188754)


I'm not sure if this is related to language of just a pagination issue. It also looks like it's happening with Orgs and People (in Tout Culture)
Let me know if you have questions or need to screenshare tomorrow and hanks for checking.

**Comment by troughc** [comment]
@sahalali the listings look good now.  So your fix seems to have solved the issue with le poutine bar, thank you.

**Comment by troughc** [comment]
@AbhishekPAnil as per our discussion at this mornings standup, I will close and PASS this issue and we will track the display issue separately (because it is likely related to a deployment). 
TEST PASSED
