### ISSUE TITLE
Taxonomy Screens

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#565]
Here is the link to the screens: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4231-101635&mode=dev
```[tasklist]
### Listing screen
- [x] Create page layout
- [x] Toolbar and header UI
- [x] API integration
- [x] Create listing cards.
- [x] Implement footer and pagination
- [x] Delete functionality modal and api integration
- [ ] Testing
```

```[tasklist]
### Add/edit screen
- [x] Create page layout
- [x] Content UI
- [x] API Integration
- [x] Add UI for concept
- [x] API integration for concept
- [x] Add modals for concept
- [x] Testing
```

```[tasklist]
### Notes for peer review and testing
- [x] In Listing page: Test search, sort, pagination and delete taxonomy functionality.
- [ ] In select class page: Check existing fields option is only shown if the class have unmapped standard fields associated with it.
- [x] Ensure navigation to add/edit page works properly.
- [ ] In edit page: Change fields of taxonomy and save them. Reload to ensure that changes are reflected in the backend correctly. Check required fields cannot be left empty.
- [ ] In Edit/Add page: Add and remove concepts, change their order and save. Check order is preserved in the backend by reloading..
```

**Comment by sahalali** [comment]
@SyamBabu-M Can you please create subtask and prepare the estimates?

**Comment by SyamBabu-M** [comment]
I will update the estimates soon.

**Comment by sahalali** [comment]
Reference: https://docs.google.com/spreadsheets/d/10r3v9TJ3iGhfSl4wqFzFGTdJ7u3RqrDLID_0EkzEQgs/edit?usp=sharing

**Comment by SyamBabu-M** [comment]
@dev-aravind please add sort by name and created by date to get all taxonomy API.
Also the API does not provide pagination functionality. Please add that as well

**Comment by dev-aravind** [comment]
@SyamBabu-M The updated API is now available in staging.

**Comment by AbhishekPAnil** [comment]
@SyamBabu-M  @AbhishekPAnil Please note that get taxonomy api with page and limit should also be added in the read only and edit pages.For the time being I have added a hard coded value of (page=1 and limit=200) ,so that we can use the updated api in the respective screens.

**Comment by troughc** [comment]
@SyamBabu-M I added all the missing default text for taxonomies. Let me know if anything is missing.

**Comment by SyamBabu-M** [comment]
@sahalali Please add the "Disambiguating description" field in the add taxonomy API. Also please change this to send "Disambiguating description" back in get all taxonomy and get taxonomy by id API.

**Comment by troughc** [comment]
@saumier @sahalali, I have a question about searching/filtering taxonomies: as of now, can a user search (or filter) a taxonomy by entity type?  For example, I want to see all the taxonomies that are in the events workspace. Does that backend support that?

**Comment by troughc** [comment]
If taxonomy classes are available and work is in scope, please add a filter for the user. I will give you the filter name before name.

**Comment by sahalali** [comment]
> @saumier @sahalali, I have a question about searching/filtering taxonomies: as of now, can a user search (or filter) a taxonomy by entity type? For example, I want to see all the taxonomies that are in the events workspace. Does that backend support that?

Yes, the filter with "taxonomy-class" will return taxonomies based on the class selected.
Example: event-type, audience, performer-role, etc..

**Comment by troughc** [comment]
This is great @sahalali . 
@AbhishekPAnil @SyamBabu-M would it be possible to a filter to the listing page called "Class" ? The user would then use this filter to view the taxonomies from a selected class(es). 
It could be muti-select filter like those in Events. 
LEt me know if this should be in a separate issue.
Thanks.

**Comment by AbhishekPAnil** [comment]
Tested in staging:
Issues found 

**Listing page**:
1. According to the figma the disambiguating description should be shown below the taxonomy name.Now the taxonomy class is shown.Please correct if I am wrong.


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/7373e2c8-1318-4797-8565-6c14ae60d64b)

**New Taxonomy Class selection page**:
1.Validation messages not shown in new taxonomy class selection page.If a user direclty clicks on the input type instead of the class a validation message should be shown to let the user know that the class should be selected. @SyamBabu-M please discuss with @troughc regarding the validation to be shown.

2.Existing field button should be disabled if all the standard field in the specified class are already mapped .

**Edit taxonomy page**
1.For new  taxonomy with standard field : After adding the concepts one by one,I tried to changed the order of the concept and tried to rename one concept .After doing so the order returned to the previous state.
2.Updating the order of the concept doesn't seem to work after successful api updation.It also return to the previous state.
3.Disable taxonomy class in the edit page according to figma


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/acb8e8aa-45ac-4927-9716-135aaa25cb66)

4.Add required asterisk to the class and taxonomy name


![Image](https://github.com/culturecreates/footlight-app/assets/117100211/5f11bfd3-c349-4800-b6b6-f02f5ac6d141)

**Comment by troughc** [comment]
Hi @SyamBabu-M I added the taxonomy validation text to the CMS copy on the third tab for you. I also commented it so it would be easier for you to find. Thanks.

**Comment by troughc** [comment]
Tested in Chrome:
1. When you create a new taxonomy that is mapping to an existing field, the Taxonomy name* field should automatically inherit its name from the 'map to existing field' choice you make. Right now it doesn't (it remains blank). 


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/f001d321-caf9-4bd1-af85-7c83599b6d9d)




2. When you enter text into the Taxonomy name* in the field, the yellow triangle doesn't disappear (I entered it in both languages). This is before I save.  
This bug doesn't happen with the disambiguating description - that works correctly. Screenshot of bug:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/cb44588f-6200-4619-b586-2d56a7a02a31)

**Expected behaviour:** when I enter the text in the Taxonomy name field, the yellow warning triangle goes away.




3. I cannot change the "restrict user access' Admin role - dropdown doesn't work - it is always set to Admin.
Expected behavour: this field should have nothing selected by default. The user can then select Admin if they want to restrict it.


4. I deleted the Audience/Public taxonomy and then tried to add it back. It is not available in the dropdown:


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/81b0248d-39d4-4aa9-ad36-ec2ef4c90ff3)


5. When I filter by class type, the new taxonomies i created are not included - see event types, organziation types and Place types.

@SyamBabu-M I will give this back to you to work on and do more testing later. thanks!

**Comment by troughc** [comment]
to do: for Caitlin
- add the english translation for Map to existing field
- add english / french translations for  the above field (dropdown) - mapped fields

**Comment by troughc** [comment]
@SyamBabu-M I made edits in the footlight CMS copy document: https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=1720382151
For the mapped fields, I will also add them to that section. I will start it at the bottom.

**Comment by troughc** [comment]
@SyamBabu-M the mapped fields are in the spreadsheet. I greyed out taxonomies for mapped fields that are not yet included in the forms (so do not add these to the taxonomy dropdown until we add them). 
We do not yet have:
virtual location type
Roles for organizer, supporter, performer

**Comment by SyamBabu-M** [comment]
@dev-aravind There is an issue while updating the mapped field of an already-existing taxonomy. When a user changes the mapped field the taxonomy updates perfectly but the calenders API returns the initially assigned mapped field.


before updating
![Image](https://github.com/culturecreates/footlight-app/assets/139208017/56c7ebb0-1183-4bfb-975c-2d41f4d24560)

after updating


![Image](https://github.com/culturecreates/footlight-app/assets/139208017/b5d8f319-2028-43bf-b060-ba2e73e2b7fd)

**Comment by dev-aravind** [comment]
@SyamBabu-M The changes are up in staging. Please test it out and let me know if you see any issues

**Comment by troughc** [comment]
Tested staging in Chrome: 
Taxonomies is working quite well,  I  don't think there are any 'functional' bugs in that section.

There are a couple of things to fix/investigate still.

1. Remove asterisk (red star) next to "Restrict user access" field in custom fields edit screen (it is not required because you can leave it as unselected). 
@SyamBabu-M I have a question about this. How can the asterisk be there when the field does not require an input? I thought it only appeared when an input is required? 


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/0997fbe0-9c82-4341-bd5d-3520def0a526)



2. If possible: when I expand a parent node in one language, I'd like the parent node in the other language to also expand (to display the children). right now it does this:

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/dfa34c05-2982-492b-af1e-558385562db2)

3. In the Artbi calendar, I added a virtual location custom field with vocabulary. However, it doesn't appear in the UI anywhere. My expectation is that it will appear when I expand Virtual location in the Location section of the Edit event page. 

screenshot of Taxonomy I created in Artbi: 


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/8b03f7ff-c3f5-4fc2-9544-e7897b52b250)


Screenshot of Edit event page with virtual location open (Location section of form)


![Image](https://github.com/culturecreates/footlight-app/assets/64489312/a31dafc8-8fd3-4687-96ee-c3123de2585c)

**Comment by SyamBabu-M** [comment]
@troughc regarding this point 
"If possible: when I expand a parent node in one language, I'd like the parent node in the other language to also expand (to display the children). right now it does this:"

It is possible. Can we take this up as an enhancement ticket?


I have removed the required field from the admin access field. I have also removed the virtual type from the taxonomy class options.

**Comment by troughc** [comment]
> "If possible: when I expand a parent node in one language, I'd like the parent node in the other language to also expand (to display the children). right now it does this:"
It is possible. Can we take this up as an enhancement ticket?

@SyamBabu-M yes, we can put it in another ticket as an enhancement.

**Comment by troughc** [comment]
@SyamBabu-M please assign this issue to me when it is ready for testing. :)

**Comment by troughc** [comment]
Tested roles: PASSED @SyamBabu-M this is ready for production.
