### ISSUE TITLE
Search Artsdata in add/edit Event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#571]
See issue #

Prerequisite for Quick Create Organization/Person/Place. This is needed to reduce the chance of creating duplicates. When linking an event to an entity, the search should search across places, people and orgs in Footlight, and also combine the results with a search in Artsdata using the Artsdata reconciliation API.

## Current behaviour

![Image](https://github.com/culturecreates/footlight-app/assets/419491/137647da-361f-4256-8112-b4a18c590778)

## Expected behaviour

![Image](https://github.com/culturecreates/footlight-app/assets/419491/32e2134b-78a7-4e8a-90de-f0ed7ee6c66a)

**Comment by AbhishekPAnil** [comment]
Added the required UI changes.
@sahalali As discussed ,please make the changes in the backend required to add entities directly from artsdata while creating an event,organization and place.Once complete please assign this issue back to me.

**Comment by sahalali** [comment]
Backend issue can be tracked here: https://github.com/culturecreates/footlight-calendar-api/issues/661
I will let you know once done.

**Comment by sahalali** [comment]
@dev-aravind 
Please add support to include Artsdata entities in the GET /entities API response. Add a new param with a boolean value, that defines if the Artsdata entities need to be included.

**Comment by dev-aravind** [comment]
@sahalali The artsdata entities are now available in the search API

**Comment by AbhishekPAnil** [comment]
UI changes are updated in staging.

**Comment by AbhishekPAnil** [comment]
Added closes tag to PR https://github.com/culturecreates/footlight-app/pull/659

**Comment by troughc** [comment]
Tested in Chrome on Staging: 

Everything PASSED except for the following display issue:
When I search for a Location/Organizer/Performer in Events workspace, the Artsdata link isn't displayed in the dropdown (like it is when I search for Places/People/Organizations in those workspaces)
### Screenshot in Events of a search for a location (it does not display the artsdata links)
![Image](https://github.com/culturecreates/footlight-calendar-api/assets/64489312/208892f1-cc8a-4970-9d6b-928dbe82608b)

@AbhishekPAnil If this is challenging or time-consuming to fix due to how the Events workspace is set up, please log it in a separate issue as a bug and close this issue.

cc @saumier

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil If this is challenging or time-consuming to fix due to how the Events workspace is set up, please log it in a separate issue as a bug and close this issue.

I have added this feature to the event edit page and its updated in staging right now.

**Comment by saumier** [comment]
@AbhishekPAnil The disambiguating descriptions are not being displayed.

In this screen capture, the right side shows the same search returning disambiguating descriptions using the [reconciliation test bench](https://reconciliation-api.github.io/testbench/#/client/https%3A%2F%2Fapi.artsdata.ca%2Frecon).

![Image](https://github.com/culturecreates/footlight-app/assets/419491/d998b0d6-7794-4ac0-816c-4af2778c3a26)

**Comment by AbhishekPAnil** [comment]
> The disambiguating descriptions are not being displayed. 

This has been fixed and updated in staging

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
