### ISSUE TITLE
Place Screen using the old approach

### ISSUE THREAD

**Issue by sahalali** [culturecreates/footlight-app#607]

**Comment by AbhishekPAnil** [comment]
@dev-aravind Please do  a peer review of this issue in staging.
Test cases:

- [ ] 1.Add a new place from the user typed keyword.
- [ ] 2.Update an existing place in footlight from the search dropdown.
- [ ] 3.Add a place from artsdata using the search dropdown.
- [ ] 4.Check if validations and notification messages are shown correctly.

**Comment by dev-aravind** [comment]
@AbhishekPAnil I did a round of peer review for you, mostly I found everything to be fine except some validation issues. 



![Image](https://github.com/culturecreates/footlight-app/assets/132546883/207f48b3-76c7-43d3-af24-4e9f12e87b77)


![Image](https://github.com/culturecreates/footlight-app/assets/132546883/2ce0eb36-d00f-4d71-943d-a119de3dc412)

**Comment by troughc** [comment]
### Guest login test
1. I get the same error as I got with people and orgs as a guest. When I try to load a Place from the "search for another instance" screen - I get a 404 errror. I think it's because it is trying to load the edit screen and I am a guest.
I can load the place from the Place list as read only.

2. Create and update a place as a guest: PASS

3. lower priority issue with Contained in Place that we could maybe fix later (cc @saumier ). 
- this field only searches for Places that have been added to Footlight - It doesn't search Artsdata. 
- I tested this with "Place des arts" and "Place des Arts - Cinquième Salle" I created Place des Arts - Cinquième Salle first and wasn't able to add Place Des Arts as the parent building.  as a workaround I saved Place des Arts - Cinquième Salle, then added Place des Arts to footlight, and then linked them using Contained in Place.

### Admin login tests
 1. Update someone else's place: PASSED
 2. delete a place from footlight: PASSED
 3. Create a place: PASSED

**Comment by AbhishekPAnil** [comment]
_I get the same error as I got with people and orgs as a guest. When I try to load a Place from the "search for another instance" screen - I get a 404 errror. I think it's because it is trying to load the edit screen and I am a guest.
I can load the place from the Place list as read only._
 
This is issue fixed and updated in staging.

_lower priority issue with Contained in Place that we could maybe fix later (cc @saumier ).

this field only searches for Places that have been added to Footlight - It doesn't search Artsdata.
I tested this with "Place des arts" and "Place des Arts - Cinquième Salle" I created Place des Arts - Cinquième Salle first and wasn't able to add Place Des Arts as the parent building. as a workaround I saved Place des Arts - Cinquième Salle, then added Place des Arts to footlight, and then linked them using Contained in Place._


This is linked to issue 
https://github.com/culturecreates/footlight-app/issues/571 and https://github.com/culturecreates/footlight-calendar-api/issues/661

**Comment by sahalali** [comment]
Issue culturecreates/footlight-calendar-api/issue#661 is done.

**Comment by troughc** [comment]
Tested the following Guest issue in Staging: **PASSED**
_I get the same error as I got with people and orgs as a guest. When I try to load a Place from the "search for another instance" screen - I get a 404 errror. I think it's because it is trying to load the edit screen and I am a guest.
I can load the place from the Place list as read only._

tested adding a new place as a guest: PASSED
Update place as a guest (place created by me): PASSED
tested other guest permissions: PASSED 


General testing (both as guest and admin) of searching, deleting, adding events etc. PASSED.

**Comment by troughc** [comment]
@saumier I am moving this to DONE. However, you may want to test it as well if you have time.

**Comment by saumier** [comment]
@troughc @sahalali Place de la Francophonie should be shown **once** in CMS since the ID is K5-394 for both the one in CMS and the one found in Artsdata.

**Comment by troughc** [comment]
Moving the remaining issues over to https://github.com/culturecreates/footlight-calendar-api/issues/328 and closing this.
PASSED
Note: there are a couple small issues that affect Place screens but they are captured in https://github.com/culturecreates/footlight-app/issues/457 (no warning when you click the breadcrumb for example)
