### ISSUE TITLE
Add Event status

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#63]
As a user, when I create an event the default status is always "Scheduled". I can change this to "Cancelled" or "Postponed". The constants from schema.org should be used in the code: https://schema.org/EventStatusType

**Comment by troughc** [comment]
Tested on Chrome 
I can change the status and save (worked with Marianna Mazza)
- Passed so will close. 
- 
HOWEVER, @saumier  I tried change Guylaine Tanguay (to canceled and to scheduled) and it disappeared from the list).I cannot reproduce this nor can I find that eventa anywhere anymore. Maybe because it is an event that happened in the past? But then why was it in the list to begin with?

**Comment by saumier** [comment]
@troughc We discussed at our standup meeting this morning and this seems to be a side effect of the change to optional time. I am closing because it cannot be reproduced.
