### ISSUE TITLE
Add HTML Classes to facilitate integration tests

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#662]
As a member of the QA test, I would like my integration tests to be less brittle so they do not easily break due to small changes in the HTML layout. The goal it to have a full set of regression tests that cover all our main functionality.

Proposed solution:  Kim is asking that we add HTML classes as per this recommendation. Please review and lets discuss to see if this is the right approach for us.
https://docs.cypress.io/guides/references/best-practices#Selecting-Elements

**Comment by AbhishekPAnil** [comment]
Added HTML classes for antd components in event form and updated the same in staging.

**Comment by troughc** [comment]
To discuss: when to wrok on HTML classes for the rest of the application - @saumier can we discuss?

**Comment by AbhishekPAnil** [comment]
Estimate for Organizations,People,Places,Settings(Users) and Taxonomies - 21.5h
1.Organization Listing page-1.5h
2.People Listing page-1.5h
3.Places listing page -1.5h
4.Settings(users) listings page-2.5h
5.Taxonomies Listing page-1.5h
6.Organizations Read only page -2h
7.People read only page-1h
8.Places read only page-2h
9.Settings(user read only )-1h
10.Organization form-1h
11.Person form-1h
12.Place form - 3h
13.Taxonomy form-2h

Since we have data centric approach for person and organization form,the data-cy attributes may be same for the components used in both pages.I am estimating assuming that Kim won't have a problem with this approach.

**Comment by AbhishekPAnil** [comment]
The data-cy attributes for all the pages are done and updated in staging and in production.Moving this to Todo ,if Kim requires any additional changes we can implement it in this issue.
