### ISSUE TITLE
Recurring dates

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#73]
Recurring dates and complex event series.

**Comment by saumier** [comment]
Estimate: 2 days remaining

**Comment by AbhishekPAnil** [comment]
@SuhailAliyar Need additional backend changes for "MONTHLY" frequency in addition to "DAILY,"CUSTOM" and "WEEKLY".

**Comment by troughc** [comment]
@AbhishekPAnil @SuhailAliyar We can add Monthly at a later time. It does not need to be implement before MVP

**Comment by troughc** [comment]
@AbhishekPAnil here are the translations needed for the 'Duplicate times' module. Please note the capitalization and slight modifications to text:


![Image](https://user-images.githubusercontent.com/64489312/225640992-ea5ea99f-04a8-46dc-a7c6-d292335712a5.png)

**Translations (with minor changes to the english text)**
TITLE Duplicate times - Dupliquer les heures

Replace the times on the following dates: - Remplacer les heures aux dates suivantes :

(The dates you should have already)

OPTION  Select all - Sélectionner tout

BUTTONS Cancel  Apply - Annuler Appliquer


And for this one (add this time):


![Image](https://user-images.githubusercontent.com/64489312/225644301-1dc07097-8aa9-46b8-a37b-754200a2c574.png)

**Translations:** 
Add time to all dates - Ajouter l'heure à toutes les dates
Cancel Add - Annuler Ajouter



![Image](https://user-images.githubusercontent.com/64489312/225646585-837217fb-4750-47fe-9599-56242ad3d691.png)

**Translations:**
Are you sure? This action cannot be undone.
Vous êtes sûr de vous ? Cette action ne peut être annulée.
Cancel OK - Annuler OK

**Comment by saumier** [comment]
@troughc Please test is staging.

**Comment by troughc** [comment]
Tested staging on Chrome

Created this event: http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/6419aac98b67f700649a70fc

These issues are not in order of importance - Issue 4 and 5 are more important.

1. When I reopen the Edit dates module, sometimes the calendar on the left appears with months scrolled to the top rather than focused on the selected month. This happened twice, in the case below it was after I published the event and then reopened it and reentered the module. It should be focused on the month with the selected dates.

![Image](https://user-images.githubusercontent.com/64489312/226616064-760ffba9-726c-4b73-a377-46bf6713f3be.png)

2. I. would like to request changing the main button name in Edit dates module from "Add dates" to "Add". The reason is that sometimes I am only adding times (not dates).

3. When I click + Add another time, to a time at the bottom of the displayed list, the Start and End time fields are displayed but not the actions options (Add button and checkbox to apply to all dates). Screenshot:

![Image](https://user-images.githubusercontent.com/64489312/226616993-da8a95ba-4b7f-4db5-96d4-be33e25d06ce.png)

Ideally the action options should be displayed because it is easy to mistakenly click the Add dates button which would close the edit dates module without adding my new time(s) to the event. And I have no way of knowing. Screenshot of what I think should be displayed when I click + Add another time: 

![Image](https://user-images.githubusercontent.com/64489312/226618225-07d4f683-ddb3-4308-a141-14691bc7101b.png)

4. when I clicked the cancel button in edit dates module after selecting + Add another time:  when I reenter the module, the UI is 'frozen' and  the + Add another time option is missing from the date I previously selected it for. Screenshot shows option missing from middle date:

![Image](https://user-images.githubusercontent.com/64489312/226624102-7f475d33-8765-408c-8baf-9d908c63e6cf.png)

Steps:
Click + Add another time
If you Click the Add button, works as expected. Instead click Cancel.
The module is displayed with the + Add another time missing from the date. This persists until you use another date and click the Add button (which seems to clear the bug).


5. When I add a new time to a date but I don't fill in any time, the current local time is added. 


![Image](https://user-images.githubusercontent.com/64489312/226625893-f1a6043f-48a4-4175-973f-b6f80981fab3.png)

6. When I click Add dates, the module closes but it flashes once (I see it flash once before it disappears).
7. After I leave the event, edit custom module, I can no longer selecte dates in the date range field in the main event. 
8. The second time I published this event, I tried to come back in and got this error.


![Image](https://user-images.githubusercontent.com/64489312/226632049-fafb2371-39a0-4d06-8122-88c70f63e02c.png)


I will reset my machine and do more testing @AbhishekPAnil

**Comment by troughc** [comment]
Test results:
@AbhishekPAnil  most parts are working really well. I was able to easily create daily and weekly events. Custom events works too accept for a few issues with the date-time tag. Here are some findings:

1. The Publish action is not working on first try. It works the second time you try.
2. In the custom dialog: the tag doesn't update with TIMES inside the custom dialog as you make changes to  Time. It does update with dates. It would be helpful if you could also see the times update. Note that after you click the Add button and add them to your event details (before saving), the tag seems to update in both places.

3. Found an issue with the tag display in event details: To see it go to. http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/641daaadaf15d1006484774b

> 1. open the event:  the tag when you come into the event says 10 dates, 10 times. This is not correct, it is actually 8 dates, 10 times. 
> 2. Click Edit to enter the custom dialog - the tag is correct (8 dates, 10 times).  Click the Add button.
> 3. The tag is now correct in the event details field (8 dates, 10 times). 
> 4. Click save to close the event. Then go back in. The tag is wrong again (10 dates, 10 times).

4. For a weekly event that spans weeks, but is only occurring on one or two days: there is a display issue after you use the edit button.

Steps to recreate:

> 1. Create a weekly event with one event per week for 2 weeks. The tag is correct in the event details (for example a weekly event that happens on monday for 2 weeks shows 2 dates on the tag). 
> 2. Click the Edit button, the tag in the custom dialog still shows 2 dates. 
> 3. Click Add. The tag in the event details page now show the number of dates in the date range (for example 12 dates instead of 2).
>

**Comment by troughc** [comment]
@AbhishekPAnil I have spent quite a bit trying out Custom recurring dates. When you select Custom from the dropdown, I think the Edit button should appear right away. You should not be required to set a date range. Rather, let those who chose Custom from the dropdown select the dates in the custom / Edit dialog (Modal). 

I have written some documentation about recurring events here if you want to take a look (it's a work in progress). Maybe it can help: https://footlight.gitbook.io/footlight-cms-guide/events-workspace/adding-a-new-event/adding-a-recurring-event

**Comment by troughc** [comment]
As discussed with Abhishek- also requested a text change on tags from 'events' to 'occurences' (eng) and 'occurences' (fr)

**Comment by AbhishekPAnil** [comment]
> As discussed with Abhishek- also requested a text change on tags from 'events' to 'occurences' (eng) and 'occurences' (fr)

@troughc I have updated staging with thr required text changes.

**Comment by troughc** [comment]
Thanks @AbhishekPAnil the text update looks good. Should I continue testing?

**Comment by AbhishekPAnil** [comment]
> Thanks @AbhishekPAnil the text update looks good. Should I continue testing?

Yes ,please.

**Comment by troughc** [comment]
Test on chrome:
Test one - weekly recurring event: http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/642312950d7d300064f7b998
Simple set up without using the edit module: PASSED
Note: I would like to see how this looks on a calendar.
Note:

**Comment by AbhishekPAnil** [comment]
@troughc I have added the fix for the issues (1) and (2) mentioned above and updated the same in staging.

**Comment by troughc** [comment]
@AbhishekPAnil issues (1) and (2) look good; but when I was testing #2 above I noticed  this:

I created a weekly recurring evnet and then went into the edit dialog to add times. The number of occurences doubled when I added a time to a date doubled. See this event (the number of occurences should be 4, not 8). It also became editable again (the date range) after I saved the event as draft and went back in.

http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/642453720d7d300064f7dad1

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil issues (1) and (2) look good; but when I was testing #2 above I noticed  this:
> 
> I created a weekly recurring evnet and then went into the edit dialog to add times. The number of occurences doubled when I added a time to a date doubled. See this event (the number of occurences should be 4, not 8). It also became editable again (the date range) after I saved the event as draft and went back in.
> 
> http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/642453720d7d300064f7dad1

@troughc I have solved and updated the fix in staging.Please do check it out.

**Comment by troughc** [comment]
Tested in staging on Chrome: PASSED
