### ISSUE TITLE
Image cropper: positioning aspect ratios not working as expected

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#771]
Display of image positioning for a ratio does not persist if I switch back and forth between the two ratios (before saving). 
Steps to reproduce
1. In staging, I opened this event: http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/651f491d5cc7560064504ad1
2. Click edit (for the image)
3. Reposition the Large image, then click to see the thumbnail and reposition the thumbnail
4. click to see the Large image - it has reverted to the original positioning
5. Click to see the thumbnail image - it has reverted to its original positioning.
6. NOTE: If you position both and then save, it will save properly. This is a display issue.
7. When I click Save (For the event), I am getting the popup message that I have unsaved changes - this is probably covered in https://github.com/culturecreates/footlight-app/issues/253

**Comment by AbhishekPAnil** [comment]
After debugging :
The issue was caused because once the user changes the cropped area values the initial values were not set again,instead it was having the previously set initial values.Hence the bug occcured.

Fix:
Initial value state for both thumbnail and large images are set once the user moves the cropped or area.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
