### ISSUE TITLE
when an option is selected from the filter, make sure it remains in the list after closing and clearing a search.

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#819]
Put the selected names at the top - in the case of users, put them just below the line that follows My events.
This issue happens with any filter that has a search field.

**Comment by AbhishekPAnil** [comment]
Blocker:
A user can select multiple search filters (organization or users).After he refresh the page the selected organizations/users should beshown as checked in the dropdown.Right now it is difficult to get the all the selected entity data all at once ,since we don't support batch get request with id's for organization or users.

**Comment by AbhishekPAnil** [comment]
This is issue dependent  on https://github.com/culturecreates/footlight-calendar-api/issues/821

**Comment by AbhishekPAnil** [comment]
@troughc The UI changes updated in staging.

**Comment by AbhishekPAnil** [comment]
Added closes tag to commit [efdfd63](https://github.com/culturecreates/footlight-app/pull/839/commits/efdfd63f506cfb7ddb9a348a8bd9254d74a48b1e)
