### ISSUE TITLE
Use the "thumbnail" image in the CMS EVENT listing screens, so it has be the same aspect ratio as the website.

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#843]
Use the "thumbnail" image aspect ratios in the CMS EVENT listing screen, so it will be the same aspect ratio as on the website.

Nice to have: if it is easy, check if the "thumbnail" image should be used as the thumbnail of the event image on the event details page. That would address Caitlin's comment on the image being squished and also serve the purpose of visually showing the thumbnail aspect ratio.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED

Wow, looks great @AbhishekPAnil ! 
one question: the little thumbnail above (on the Edit page). You didn't update it correct? It still looks squishy to me, especially on the Tout Culture pages

**Comment by AbhishekPAnil** [comment]
@troughc .It wasn't me,the changes were done by @SyamBabu-M .

**Comment by SyamBabu-M** [comment]
@troughc The images in the thumbnail are updated. The images in the thumbnail currently have an aspect ratio of 5/4 for tout culture. Since we have fixed the height at 48px the width is set according to the aspect ratio. If required, we can try changing the height to make it look less squishy.

**Comment by SyamBabu-M** [comment]
<img width="1440" alt="Screenshot 2023-12-18 at 6 33 09 PM" src="https://github.com/culturecreates/footlight-app/assets/139208017/f3765228-55ea-44e7-8d3b-f7ec14ca5ce1">
when height is fixed(48px)


<img width="1440" alt="Screenshot 2023-12-18 at 6 34 07 PM" src="https://github.com/culturecreates/footlight-app/assets/139208017/22788616-d2ef-438f-8901-2e6b9c5b9cd6">
when width is fixed(48px)

**Comment by troughc** [comment]
I like it when the height is fixed (first one).

**Comment by saumier** [comment]
@SyamBabu-M @AbhishekPAnil In the standup meeting this morning I suggested using a simpler approach to fix this "thumbnail" images in the Event listing screens. Instead of adding the aspect ratio, you can just set the height and leave the width alone. Here are 2 screen shots on Safari before and after.  In general, I'll challenge you to always first simplify code before adding more code. 

## Before with unnecessary aspect-ratio styling

![Image](https://github.com/culturecreates/footlight-app/assets/419491/be0fe960-a6e9-447a-a53e-582736e742ec)

## After with aspect-ratio style removed, height set and width left alone.

![Image](https://github.com/culturecreates/footlight-app/assets/419491/55246eae-a3b6-40ee-af46-4a0b27c18421)

**Comment by AbhishekPAnil** [comment]
@saumier Thank you.We will make sure to implement this.
