### ISSUE TITLE
Duplicate Event

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#94]
As a CMS user, I can duplicate an event to reduce my workload when an event repeats at different locations or when a past event returns.

**Client input**: Event duplicator with access to past events - pet peeve of her contributors is not being able to use another event as their 'template'.

### Find the Figma design in Sprint 14 (english and french) - English shown here:

**Event page display:**

![Image](https://user-images.githubusercontent.com/64489312/221892245-cbc10abe-0b5a-48b5-8b92-108f67b70bd6.png)

**right-click menu items for the event you want to duplicate in the Event Listing page - according to user profiles.:**

![Image](https://user-images.githubusercontent.com/64489312/221892289-59a1abf5-1d6c-46f8-8c97-56d9570e1fc0.png)

###  1 - Multiple locations
1. Create an event at location A
2. Duplicate the event
3. Change the location of the duplicated event to Location B
4. Publish both events and check that they appear in the frontend

### 2 - Performer returns for a new tour at the same place
1. Search for a past event A (happened in the past)
2. Duplicate the event
3. Change the date of the duplicated event to the future
4. Publish the duplicated event and check that it appears in the frontend

**Comment by saumier** [comment]
@troughc This is high priority for Isabelle and Maude, but how will it work? Is there a Figma design?

**Comment by troughc** [comment]
Yes @saumier. Please see Figma Sprint 14 for design.

**Comment by troughc** [comment]
@saumier I have user stories (slightlyn edited) from Maude about two cases:
- Need for an event duplicator 
- Need to be able to see/access past events to add new dates  (update a past existing event to continue into the present and future). 
-
I thought I would add them here, should they also go somewhere else?
### User stories - for using an event duplicator

1. There is a new series like conte musical. I create and event for la Library 1. I then want to duplicate this event for Libraries 2-6.
2. La fête nationale happens every year. In this case, I want to duplicate it because it is a different event each year. 
3. Marianna Mazza does a show 2 times in the same year at co-motion. It's not the same show, but some of the information is the same so I want to duplicate the previous event. 

### User stories - for adding new dates to a past event (extending an event series), i.e. filter that lets me find past events and then update them.

1. "conte et compagnie" is a series of activities presented by la Ville over multiple years. The description and hour are always the same. I could use the same event and add new dates, even more so if we have the sorting by rarety on the front end.
2. I have an artist who does a podcast, every season I confirm that she's continuing her podcast for the next season, but sometimes I'm a little bit late and her event ends up in the past events. I want to go and get the event and then add the (new) dates, because this podcast is not a new event (it's part of the same series).

**Comment by AbhishekPAnil** [comment]
ESTIMATE : 2.5 hrs

Subtasks
1.Add duplicate option to event options dropdown and the functionality to redirect from event list page to add/edit event page.
2.Add duplicate event id as query param to the url and api integration to fetch data using query param .

**Comment by AbhishekPAnil** [comment]
@saumier ,@SuhailAliyar We may need backend changes regarding the image upload for duplicate events.Since the user may not be uploading the image for a duplicate event,it is difficult to get the already uploaded image details while saving a duplicate event.

I think we can discuss this in our stand up meeting.

**Comment by saumier** [comment]
@troughc Please test in staging.

**Comment by saumier** [comment]
@SuhailAliyar @AbhishekPAnil Bug when duplicating an event. The duplicate event must not copy the same event sameAs. For example, if an event has a sameAs K23-11 then the duplicated event must not copy over the Artsdata event Id. The event sameAs must by dropped when duplicating events. The sameAs of the Place, People etc should be copied. Only the event sameAs must not.

**Comment by SuhailAliyar** [comment]
@saumier I could not reproduce this issue in staging.
I created a [duplicate](http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/6422b70faf15d1006484ec26) of http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/642282e8af15d1006484db82.

The copy doesn't have the sameAs in it. 
cc @AbhishekPAnil
