### ISSUE TITLE
People: images on list page in CMS look stretched

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#955]
images of people in Signe Laval people list look elongated

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/f9764769-76f8-4db5-b1c6-8f8804a20eb2)

**Comment by SyamBabu-M** [comment]
@saumier @AbhishekPAnil 
I looked into the comments of PR. And I have updated the styles as you mentioned.

I just want to mention that adding object-fit: cover will make the image fill the entire 40*40 container. But this can cause a portion of the image to be cropped if the images are not square in dimension.

![Image](https://github.com/culturecreates/footlight-app/assets/139208017/663c3504-02e3-4bcf-baa2-4adb1438fb5b)

object-fit: contain on the other hand will ensure that the entire image that the user uploaded will be shown.

**Comment by saumier** [comment]
@SyamBabu-M Looks good. Since the images are all different sizes, the thumbnail view would loose a consistent look and feel. I think using `object-fit: flow` on the list with the small thumbnails, like in events list, is the way to go. And the full image can be seen on the details view with `object-fit: contain`.
