### ISSUE TITLE
CMS: Optimise the API calls

### ISSUE THREAD

**Issue by sahalali** [culturecreates/footlight-app#983]
Please try optimizing the API calls and make sure that doesn't affect the user experience.

1. When a user clicks on the "Events" tab in CMS, then there are three API calls triggered in parallel.
The API calls are event listing, user listing, and organization listing.
In my opinion, we can trigger the user listing and organization listing API calls after receiving the response of the event listing API call. This can reduce the queue time for the API.
Food for thought: The user listing and organization listing API calls in this case can be triggered when the user tries to select the user/organization to filter.
2. _Analyse the API calls in the CMS and see if any change required_

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil 
Look into the calendar id getting undefined while the api is slow.

**Comment by SyamBabu-M** [comment]
Todo - 

1- Look at the event listing page for APIs that are run in parallel. Separate these into series so that the page can load once the event listing API has been called. The rest of the APIs like get-users and get-organizations can be called once the user interacts with the said component.

2 - Look into forms and remove the initial API call for searching organizations, people, and places so that the form can load without them. These APIs can be called once the user interacts with the said component.

**Comment by troughc** [comment]
Tested: looks okay to me. PASSED
 @sahalali maybe you want to take a look at this before deploying

**Comment by saumier** [comment]
@sahalali Lets deploy!
